source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'SDWebImage', :git => 'git@github.com:rs/SDWebImage.git', :branch => '4.x'
pod 'DACircularProgress'

end
